[application]
name = "r2048"
default_platform = "web"
out_dir = "dist"
asset_dir = "../public"
sub_package = "src/web"

[web.app]
title = "rust-2048"

[web.watcher]
reload_html = true
watch_path = ["src"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
