[application]
name = "rust-2048"
default_platform = "web"
out_dir = "../../dist"
asset_dir = "../../public"
sub_package = "packages/client"

[web.app]
title = "rust-2048"

[web.watcher]
reload_html = true
watch_path = ["src"]
index_on_404 = true

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
